# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytalic2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.main_widget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.main_widget)
        self.verticalLayout.setContentsMargins(2, 2, 3, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.main_layout = QtGui.QVBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.char_selector_list = QtGui.QListWidget(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_selector_list.sizePolicy().hasHeightForWidth())
        self.char_selector_list.setSizePolicy(sizePolicy)
        self.char_selector_list.setMaximumSize(QtCore.QSize(16777215, 70))
        self.char_selector_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.char_selector_list.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.char_selector_list.setTabKeyNavigation(True)
        self.char_selector_list.setIconSize(QtCore.QSize(60, 60))
        self.char_selector_list.setFlow(QtGui.QListView.LeftToRight)
        self.char_selector_list.setUniformItemSizes(True)
        self.char_selector_list.setObjectName(_fromUtf8("char_selector_list"))
        self.main_layout.addWidget(self.char_selector_list)
        self.view_layout = QtGui.QHBoxLayout()
        self.view_layout.setSpacing(5)
        self.view_layout.setObjectName(_fromUtf8("view_layout"))
        self.stroke_selector_list = QtGui.QListWidget(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_selector_list.sizePolicy().hasHeightForWidth())
        self.stroke_selector_list.setSizePolicy(sizePolicy)
        self.stroke_selector_list.setMaximumSize(QtCore.QSize(60, 16777215))
        self.stroke_selector_list.setTabKeyNavigation(True)
        self.stroke_selector_list.setDragEnabled(True)
        self.stroke_selector_list.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.stroke_selector_list.setIconSize(QtCore.QSize(60, 60))
        self.stroke_selector_list.setUniformItemSizes(True)
        self.stroke_selector_list.setObjectName(_fromUtf8("stroke_selector_list"))
        self.view_layout.addWidget(self.stroke_selector_list)
        self.main_splitter = QtGui.QSplitter(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_splitter.sizePolicy().hasHeightForWidth())
        self.main_splitter.setSizePolicy(sizePolicy)
        self.main_splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName(_fromUtf8("main_splitter"))
        self.main_view_tabs = QtGui.QTabWidget(self.main_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_view_tabs.sizePolicy().hasHeightForWidth())
        self.main_view_tabs.setSizePolicy(sizePolicy)
        self.main_view_tabs.setMouseTracking(False)
        self.main_view_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.main_view_tabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_view_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.main_view_tabs.setObjectName(_fromUtf8("main_view_tabs"))
        self.dwg_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwg_tab.sizePolicy().hasHeightForWidth())
        self.dwg_tab.setSizePolicy(sizePolicy)
        self.dwg_tab.setAcceptDrops(True)
        self.dwg_tab.setObjectName(_fromUtf8("dwg_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dwg_tab)
        self.verticalLayout_2.setMargin(1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dwg_area = DrawingArea(self.dwg_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwg_area.sizePolicy().hasHeightForWidth())
        self.dwg_area.setSizePolicy(sizePolicy)
        self.dwg_area.setMouseTracking(True)
        self.dwg_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dwg_area.setAcceptDrops(True)
        self.dwg_area.setFrameShape(QtGui.QFrame.Panel)
        self.dwg_area.setFrameShadow(QtGui.QFrame.Sunken)
        self.dwg_area.setLineWidth(2)
        self.dwg_area.setMidLineWidth(0)
        self.dwg_area.setObjectName(_fromUtf8("dwg_area"))
        self.verticalLayout_2.addWidget(self.dwg_area)
        self.main_view_tabs.addTab(self.dwg_tab, _fromUtf8(""))
        self.glyph_dwg_tab = QtGui.QWidget()
        self.glyph_dwg_tab.setObjectName(_fromUtf8("glyph_dwg_tab"))
        self.horizontalLayout = QtGui.QVBoxLayout(self.glyph_dwg_tab)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.stroke_dwg_area = DrawingArea(self.glyph_dwg_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_dwg_area.sizePolicy().hasHeightForWidth())
        self.stroke_dwg_area.setSizePolicy(sizePolicy)
        self.stroke_dwg_area.setMouseTracking(True)
        self.stroke_dwg_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.stroke_dwg_area.setFrameShape(QtGui.QFrame.Panel)
        self.stroke_dwg_area.setFrameShadow(QtGui.QFrame.Sunken)
        self.stroke_dwg_area.setLineWidth(2)
        self.stroke_dwg_area.setObjectName(_fromUtf8("stroke_dwg_area"))
        self.horizontalLayout.addWidget(self.stroke_dwg_area)
        self.main_view_tabs.addTab(self.glyph_dwg_tab, _fromUtf8(""))
        self.preview_tab = QtGui.QWidget()
        self.preview_tab.setObjectName(_fromUtf8("preview_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.preview_tab)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.layout_reset_button = QtGui.QPushButton(self.preview_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_reset_button.sizePolicy().hasHeightForWidth())
        self.layout_reset_button.setSizePolicy(sizePolicy)
        self.layout_reset_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.layout_reset_button.setObjectName(_fromUtf8("layout_reset_button"))
        self.horizontalLayout_2.addWidget(self.layout_reset_button)
        self.layout_combo = QtGui.QComboBox(self.preview_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_combo.sizePolicy().hasHeightForWidth())
        self.layout_combo.setSizePolicy(sizePolicy)
        self.layout_combo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.layout_combo.setFrame(True)
        self.layout_combo.setObjectName(_fromUtf8("layout_combo"))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.layout_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.layout_combo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.preview_area = LayoutArea(self.preview_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_area.sizePolicy().hasHeightForWidth())
        self.preview_area.setSizePolicy(sizePolicy)
        self.preview_area.setMouseTracking(True)
        self.preview_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.preview_area.setFrameShape(QtGui.QFrame.Panel)
        self.preview_area.setFrameShadow(QtGui.QFrame.Sunken)
        self.preview_area.setLineWidth(2)
        self.preview_area.setObjectName(_fromUtf8("preview_area"))
        self.verticalLayout_3.addWidget(self.preview_area)
        self.main_view_tabs.addTab(self.preview_tab, _fromUtf8(""))
        self.property_tabs = QtGui.QTabWidget(self.main_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.property_tabs.sizePolicy().hasHeightForWidth())
        self.property_tabs.setSizePolicy(sizePolicy)
        self.property_tabs.setObjectName(_fromUtf8("property_tabs"))
        self.stroke_prop_tab = QtGui.QWidget()
        self.stroke_prop_tab.setObjectName(_fromUtf8("stroke_prop_tab"))
        self.formLayout_3 = QtGui.QFormLayout(self.stroke_prop_tab)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_17 = QtGui.QLabel(self.stroke_prop_tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.stroke_prop_tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.stroke_prop_tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.position_x_spin = QtGui.QDoubleSpinBox(self.stroke_prop_tab)
        self.position_x_spin.setKeyboardTracking(False)
        self.position_x_spin.setDecimals(1)
        self.position_x_spin.setMinimum(-100000.0)
        self.position_x_spin.setMaximum(100000.0)
        self.position_x_spin.setObjectName(_fromUtf8("position_x_spin"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.position_x_spin)
        self.position_y_spin = QtGui.QDoubleSpinBox(self.stroke_prop_tab)
        self.position_y_spin.setKeyboardTracking(False)
        self.position_y_spin.setDecimals(1)
        self.position_y_spin.setMinimum(-100000.0)
        self.position_y_spin.setMaximum(100000.0)
        self.position_y_spin.setObjectName(_fromUtf8("position_y_spin"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.position_y_spin)
        self.behavior_combo = QtGui.QComboBox(self.stroke_prop_tab)
        self.behavior_combo.setFrame(True)
        self.behavior_combo.setObjectName(_fromUtf8("behavior_combo"))
        self.behavior_combo.addItem(_fromUtf8(""))
        self.behavior_combo.addItem(_fromUtf8(""))
        self.behavior_combo.addItem(_fromUtf8(""))
        self.behavior_combo.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.behavior_combo)
        self.label_20 = QtGui.QLabel(self.stroke_prop_tab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self.stroke_override_nib_angle = QtGui.QCheckBox(self.stroke_prop_tab)
        self.stroke_override_nib_angle.setObjectName(_fromUtf8("stroke_override_nib_angle"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.stroke_override_nib_angle)
        self.label_21 = QtGui.QLabel(self.stroke_prop_tab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_21)
        self.stroke_nib_angle_spin = QtGui.QSpinBox(self.stroke_prop_tab)
        self.stroke_nib_angle_spin.setWrapping(True)
        self.stroke_nib_angle_spin.setMaximum(90)
        self.stroke_nib_angle_spin.setProperty("value", 40)
        self.stroke_nib_angle_spin.setObjectName(_fromUtf8("stroke_nib_angle_spin"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.stroke_nib_angle_spin)
        self.property_tabs.addTab(self.stroke_prop_tab, _fromUtf8(""))
        self.char_prop_tab = QtGui.QWidget()
        self.char_prop_tab.setObjectName(_fromUtf8("char_prop_tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.char_prop_tab)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_13 = QtGui.QLabel(self.char_prop_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.override_char_set = QtGui.QCheckBox(self.char_prop_tab)
        self.override_char_set.setObjectName(_fromUtf8("override_char_set"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.override_char_set)
        self.label_14 = QtGui.QLabel(self.char_prop_tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.char_prop_tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.char_prop_tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.char_width_spin = QtGui.QDoubleSpinBox(self.char_prop_tab)
        self.char_width_spin.setWrapping(True)
        self.char_width_spin.setDecimals(1)
        self.char_width_spin.setMinimum(2.0)
        self.char_width_spin.setMaximum(10.0)
        self.char_width_spin.setSingleStep(0.5)
        self.char_width_spin.setProperty("value", 4.0)
        self.char_width_spin.setObjectName(_fromUtf8("char_width_spin"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.char_width_spin)
        self.left_space_spin = QtGui.QDoubleSpinBox(self.char_prop_tab)
        self.left_space_spin.setWrapping(True)
        self.left_space_spin.setDecimals(1)
        self.left_space_spin.setMaximum(3.0)
        self.left_space_spin.setSingleStep(0.1)
        self.left_space_spin.setProperty("value", 1.0)
        self.left_space_spin.setObjectName(_fromUtf8("left_space_spin"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.left_space_spin)
        self.right_space_spin = QtGui.QDoubleSpinBox(self.char_prop_tab)
        self.right_space_spin.setWrapping(True)
        self.right_space_spin.setDecimals(1)
        self.right_space_spin.setMaximum(3.0)
        self.right_space_spin.setSingleStep(0.1)
        self.right_space_spin.setProperty("value", 1.0)
        self.right_space_spin.setObjectName(_fromUtf8("right_space_spin"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.right_space_spin)
        self.property_tabs.addTab(self.char_prop_tab, _fromUtf8(""))
        self.char_set_prop_tab = QtGui.QWidget()
        self.char_set_prop_tab.setObjectName(_fromUtf8("char_set_prop_tab"))
        self.formLayout = QtGui.QFormLayout(self.char_set_prop_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.char_set_prop_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.base_height_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.base_height_spin.setWrapping(True)
        self.base_height_spin.setFrame(True)
        self.base_height_spin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.base_height_spin.setDecimals(1)
        self.base_height_spin.setMinimum(1.0)
        self.base_height_spin.setMaximum(10.0)
        self.base_height_spin.setSingleStep(0.5)
        self.base_height_spin.setObjectName(_fromUtf8("base_height_spin"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.base_height_spin)
        self.label_3 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cap_height_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.cap_height_spin.setWrapping(True)
        self.cap_height_spin.setDecimals(1)
        self.cap_height_spin.setMinimum(0.5)
        self.cap_height_spin.setMaximum(10.0)
        self.cap_height_spin.setSingleStep(0.5)
        self.cap_height_spin.setProperty("value", 2.0)
        self.cap_height_spin.setObjectName(_fromUtf8("cap_height_spin"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cap_height_spin)
        self.label_4 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ascent_height_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.ascent_height_spin.setWrapping(True)
        self.ascent_height_spin.setDecimals(1)
        self.ascent_height_spin.setMinimum(1.0)
        self.ascent_height_spin.setMaximum(10.0)
        self.ascent_height_spin.setSingleStep(0.5)
        self.ascent_height_spin.setObjectName(_fromUtf8("ascent_height_spin"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ascent_height_spin)
        self.label_2 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_5 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.descent_height_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.descent_height_spin.setWrapping(True)
        self.descent_height_spin.setDecimals(1)
        self.descent_height_spin.setMinimum(1.0)
        self.descent_height_spin.setMaximum(10.0)
        self.descent_height_spin.setSingleStep(0.5)
        self.descent_height_spin.setObjectName(_fromUtf8("descent_height_spin"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.descent_height_spin)
        self.label_6 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.angle_spin = QtGui.QSpinBox(self.char_set_prop_tab)
        self.angle_spin.setWrapping(True)
        self.angle_spin.setMaximum(45)
        self.angle_spin.setObjectName(_fromUtf8("angle_spin"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.angle_spin)
        self.label_7 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_7)
        self.gap_height_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.gap_height_spin.setWrapping(True)
        self.gap_height_spin.setDecimals(1)
        self.gap_height_spin.setMinimum(0.5)
        self.gap_height_spin.setMaximum(4.0)
        self.gap_height_spin.setSingleStep(0.5)
        self.gap_height_spin.setProperty("value", 1.5)
        self.gap_height_spin.setObjectName(_fromUtf8("gap_height_spin"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.gap_height_spin)
        self.label_8 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.nominal_width_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.nominal_width_spin.setWrapping(True)
        self.nominal_width_spin.setDecimals(1)
        self.nominal_width_spin.setMinimum(2.0)
        self.nominal_width_spin.setMaximum(10.0)
        self.nominal_width_spin.setSingleStep(0.5)
        self.nominal_width_spin.setProperty("value", 4.0)
        self.nominal_width_spin.setObjectName(_fromUtf8("nominal_width_spin"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.nominal_width_spin)
        self.char_set_left_space_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.char_set_left_space_spin.setDecimals(1)
        self.char_set_left_space_spin.setMaximum(3.0)
        self.char_set_left_space_spin.setSingleStep(0.1)
        self.char_set_left_space_spin.setProperty("value", 1.0)
        self.char_set_left_space_spin.setObjectName(_fromUtf8("char_set_left_space_spin"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.char_set_left_space_spin)
        self.char_set_right_space_spin = QtGui.QDoubleSpinBox(self.char_set_prop_tab)
        self.char_set_right_space_spin.setDecimals(1)
        self.char_set_right_space_spin.setMaximum(3.0)
        self.char_set_right_space_spin.setSingleStep(0.1)
        self.char_set_right_space_spin.setProperty("value", 1.0)
        self.char_set_right_space_spin.setObjectName(_fromUtf8("char_set_right_space_spin"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.char_set_right_space_spin)
        self.char_set_nib_angle_spin = QtGui.QSpinBox(self.char_set_prop_tab)
        self.char_set_nib_angle_spin.setWrapping(True)
        self.char_set_nib_angle_spin.setMaximum(90)
        self.char_set_nib_angle_spin.setProperty("value", 40)
        self.char_set_nib_angle_spin.setObjectName(_fromUtf8("char_set_nib_angle_spin"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.char_set_nib_angle_spin)
        self.label_11 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.char_set_prop_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_12)
        self.guides_color_button = SelectColorButton(self.char_set_prop_tab)
        self.guides_color_button.setAutoFillBackground(False)
        self.guides_color_button.setText(_fromUtf8(""))
        self.guides_color_button.setObjectName(_fromUtf8("guides_color_button"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.guides_color_button)
        self.property_tabs.addTab(self.char_set_prop_tab, _fromUtf8(""))
        self.view_layout.addWidget(self.main_splitter)
        self.main_layout.addLayout(self.view_layout)
        self.verticalLayout.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 15))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Snap = QtGui.QMenu(self.menu_View)
        self.menu_Snap.setObjectName(_fromUtf8("menu_Snap"))
        self.menu_Stroke = QtGui.QMenu(self.menubar)
        self.menu_Stroke.setObjectName(_fromUtf8("menu_Stroke"))
        self.menu_Glyph = QtGui.QMenu(self.menubar)
        self.menu_Glyph.setObjectName(_fromUtf8("menu_Glyph"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.file_new = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/script_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_new.setIcon(icon)
        self.file_new.setObjectName(_fromUtf8("file_new"))
        self.file_open = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/script_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_open.setIcon(icon1)
        self.file_open.setObjectName(_fromUtf8("file_open"))
        self.file_save = QtGui.QAction(MainWindow)
        self.file_save.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/script_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save.setIcon(icon2)
        self.file_save.setObjectName(_fromUtf8("file_save"))
        self.file_save_as = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save_as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save_as.setIcon(icon3)
        self.file_save_as.setObjectName(_fromUtf8("file_save_as"))
        self.file_quit = QtGui.QAction(MainWindow)
        self.file_quit.setObjectName(_fromUtf8("file_quit"))
        self.edit_undo = QtGui.QAction(MainWindow)
        self.edit_undo.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow_undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_undo.setIcon(icon4)
        self.edit_undo.setObjectName(_fromUtf8("edit_undo"))
        self.edit_redo = QtGui.QAction(MainWindow)
        self.edit_redo.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow_redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_redo.setIcon(icon5)
        self.edit_redo.setObjectName(_fromUtf8("edit_redo"))
        self.edit_cut = QtGui.QAction(MainWindow)
        self.edit_cut.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_cut.setIcon(icon6)
        self.edit_cut.setObjectName(_fromUtf8("edit_cut"))
        self.edit_copy = QtGui.QAction(MainWindow)
        self.edit_copy.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/page_white_copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_copy.setIcon(icon7)
        self.edit_copy.setObjectName(_fromUtf8("edit_copy"))
        self.edit_paste = QtGui.QAction(MainWindow)
        self.edit_paste.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/page_white_paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_paste.setIcon(icon8)
        self.edit_paste.setObjectName(_fromUtf8("edit_paste"))
        self.view_reset_origin = QtGui.QAction(MainWindow)
        self.view_reset_origin.setObjectName(_fromUtf8("view_reset_origin"))
        self.view_reset_zoom = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom_actual.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_reset_zoom.setIcon(icon9)
        self.view_reset_zoom.setObjectName(_fromUtf8("view_reset_zoom"))
        self.view_guides = QtGui.QAction(MainWindow)
        self.view_guides.setCheckable(True)
        self.view_guides.setChecked(True)
        self.view_guides.setObjectName(_fromUtf8("view_guides"))
        self.view_nib_guides = QtGui.QAction(MainWindow)
        self.view_nib_guides.setCheckable(True)
        self.view_nib_guides.setChecked(True)
        self.view_nib_guides.setObjectName(_fromUtf8("view_nib_guides"))
        self.view_snap_to_axes = QtGui.QAction(MainWindow)
        self.view_snap_to_axes.setCheckable(True)
        self.view_snap_to_axes.setChecked(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/transform_move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_axes.setIcon(icon10)
        self.view_snap_to_axes.setObjectName(_fromUtf8("view_snap_to_axes"))
        self.view_snap_to_nib_axes = QtGui.QAction(MainWindow)
        self.view_snap_to_nib_axes.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/transform_path.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_nib_axes.setIcon(icon11)
        self.view_snap_to_nib_axes.setObjectName(_fromUtf8("view_snap_to_nib_axes"))
        self.view_snap_to_grid = QtGui.QAction(MainWindow)
        self.view_snap_to_grid.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/grid.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_grid.setIcon(icon12)
        self.view_snap_to_grid.setObjectName(_fromUtf8("view_snap_to_grid"))
        self.view_snap_to_ctrl_pts = QtGui.QAction(MainWindow)
        self.view_snap_to_ctrl_pts.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit_path.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_ctrl_pts.setIcon(icon13)
        self.view_snap_to_ctrl_pts.setObjectName(_fromUtf8("view_snap_to_ctrl_pts"))
        self.action_To_Strokes = QtGui.QAction(MainWindow)
        self.action_To_Strokes.setCheckable(True)
        self.action_To_Strokes.setEnabled(False)
        self.action_To_Strokes.setObjectName(_fromUtf8("action_To_Strokes"))
        self.stroke_new = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/draw_path.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stroke_new.setIcon(icon14)
        self.stroke_new.setObjectName(_fromUtf8("stroke_new"))
        self.stroke_delete = QtGui.QAction(MainWindow)
        self.stroke_delete.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stroke_delete.setIcon(icon15)
        self.stroke_delete.setObjectName(_fromUtf8("stroke_delete"))
        self.stroke_straighten = QtGui.QAction(MainWindow)
        self.stroke_straighten.setEnabled(False)
        self.stroke_straighten.setObjectName(_fromUtf8("stroke_straighten"))
        self.stroke_join = QtGui.QAction(MainWindow)
        self.stroke_join.setEnabled(False)
        self.stroke_join.setObjectName(_fromUtf8("stroke_join"))
        self.stroke_flip_x = QtGui.QAction(MainWindow)
        self.stroke_flip_x.setEnabled(False)
        self.stroke_flip_x.setObjectName(_fromUtf8("stroke_flip_x"))
        self.stroke_flip_y = QtGui.QAction(MainWindow)
        self.stroke_flip_y.setEnabled(False)
        self.stroke_flip_y.setObjectName(_fromUtf8("stroke_flip_y"))
        self.stroke_align_tangents = QtGui.QAction(MainWindow)
        self.stroke_align_tangents.setEnabled(False)
        self.stroke_align_tangents.setObjectName(_fromUtf8("stroke_align_tangents"))
        self.stroke_smooth_tangents = QtGui.QAction(MainWindow)
        self.stroke_smooth_tangents.setEnabled(False)
        self.stroke_smooth_tangents.setObjectName(_fromUtf8("stroke_smooth_tangents"))
        self.stroke_sharpen_tangents = QtGui.QAction(MainWindow)
        self.stroke_sharpen_tangents.setEnabled(False)
        self.stroke_sharpen_tangents.setObjectName(_fromUtf8("stroke_sharpen_tangents"))
        self.stroke_add_vertex = QtGui.QAction(MainWindow)
        self.stroke_add_vertex.setEnabled(False)
        self.stroke_add_vertex.setObjectName(_fromUtf8("stroke_add_vertex"))
        self.stroke_split_at_point = QtGui.QAction(MainWindow)
        self.stroke_split_at_point.setEnabled(False)
        self.stroke_split_at_point.setObjectName(_fromUtf8("stroke_split_at_point"))
        self.stroke_save = QtGui.QAction(MainWindow)
        self.stroke_save.setEnabled(False)
        self.stroke_save.setObjectName(_fromUtf8("stroke_save"))
        self.help_about = QtGui.QAction(MainWindow)
        self.help_about.setObjectName(_fromUtf8("help_about"))
        self.stroke_load = QtGui.QAction(MainWindow)
        self.stroke_load.setEnabled(False)
        self.stroke_load.setObjectName(_fromUtf8("stroke_load"))
        self.glyph_delete = QtGui.QAction(MainWindow)
        self.glyph_delete.setEnabled(False)
        self.glyph_delete.setObjectName(_fromUtf8("glyph_delete"))
        self.menuFile.addAction(self.file_new)
        self.menuFile.addAction(self.file_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_save)
        self.menuFile.addAction(self.file_save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_quit)
        self.menu_Edit.addAction(self.edit_undo)
        self.menu_Edit.addAction(self.edit_redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.edit_cut)
        self.menu_Edit.addAction(self.edit_copy)
        self.menu_Edit.addAction(self.edit_paste)
        self.menu_Snap.addAction(self.view_snap_to_axes)
        self.menu_Snap.addAction(self.view_snap_to_nib_axes)
        self.menu_Snap.addAction(self.view_snap_to_grid)
        self.menu_Snap.addAction(self.view_snap_to_ctrl_pts)
        self.menu_Snap.addAction(self.action_To_Strokes)
        self.menu_View.addAction(self.view_reset_origin)
        self.menu_View.addAction(self.view_reset_zoom)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.view_guides)
        self.menu_View.addAction(self.view_nib_guides)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.menu_Snap.menuAction())
        self.menu_Stroke.addAction(self.stroke_new)
        self.menu_Stroke.addAction(self.stroke_delete)
        self.menu_Stroke.addAction(self.stroke_straighten)
        self.menu_Stroke.addAction(self.stroke_join)
        self.menu_Stroke.addAction(self.stroke_flip_x)
        self.menu_Stroke.addAction(self.stroke_flip_y)
        self.menu_Stroke.addSeparator()
        self.menu_Stroke.addAction(self.stroke_align_tangents)
        self.menu_Stroke.addAction(self.stroke_smooth_tangents)
        self.menu_Stroke.addAction(self.stroke_sharpen_tangents)
        self.menu_Stroke.addSeparator()
        self.menu_Stroke.addAction(self.stroke_add_vertex)
        self.menu_Stroke.addAction(self.stroke_split_at_point)
        self.menu_Glyph.addAction(self.stroke_save)
        self.menu_Glyph.addAction(self.stroke_load)
        self.menu_Glyph.addAction(self.glyph_delete)
        self.menu_Help.addAction(self.help_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Stroke.menuAction())
        self.menubar.addAction(self.menu_Glyph.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.file_new)
        self.toolBar.addAction(self.file_open)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.file_save)
        self.toolBar.addAction(self.file_save_as)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_undo)
        self.toolBar.addAction(self.edit_redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_cut)
        self.toolBar.addAction(self.edit_copy)
        self.toolBar.addAction(self.edit_paste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.view_snap_to_axes)
        self.toolBar.addAction(self.view_snap_to_nib_axes)
        self.toolBar.addAction(self.view_snap_to_grid)
        self.toolBar.addAction(self.view_snap_to_ctrl_pts)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.stroke_new)
        self.toolBar.addAction(self.stroke_delete)

        self.retranslateUi(MainWindow)
        self.main_view_tabs.setCurrentIndex(0)
        self.property_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.dwg_tab), _translate("MainWindow", "Character", None))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.glyph_dwg_tab), _translate("MainWindow", "Glyph", None))
        self.layout_reset_button.setText(_translate("MainWindow", "Reset Layout", None))
        self.layout_combo.setItemText(0, _translate("MainWindow", "ABCDEFGHIJKLMNOPQRSTUVWXYZ  abcdefghijklmnopqrstuvwxyz  0123456789", None))
        self.layout_combo.setItemText(1, _translate("MainWindow", "Both fickle dwarves jinx my pig quiz", None))
        self.layout_combo.setItemText(2, _translate("MainWindow", "The five boxing wizards jump quickly", None))
        self.layout_combo.setItemText(3, _translate("MainWindow", "Fix problem quickly with galvanized jets", None))
        self.layout_combo.setItemText(4, _translate("MainWindow", "Cozy sphinx waves quart jug of bad milk", None))
        self.layout_combo.setItemText(5, _translate("MainWindow", "The quick brown fox jumps over the lazy dog", None))
        self.layout_combo.setItemText(6, _translate("MainWindow", "Pack my red box with five dozen quality jugs", None))
        self.layout_combo.setItemText(7, _translate("MainWindow", "Amazingly few discotheques provide jukeboxes", None))
        self.layout_combo.setItemText(8, _translate("MainWindow", "Painful zombies quickly watch a jinxed graveyard", None))
        self.layout_combo.setItemText(9, _translate("MainWindow", "Jack quietly moved up front and seized the big ball of wax", None))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.preview_tab), _translate("MainWindow", "Preview", None))
        self.label_17.setText(_translate("MainWindow", "Position", None))
        self.label_18.setText(_translate("MainWindow", "X", None))
        self.label_19.setText(_translate("MainWindow", "Y", None))
        self.behavior_combo.setItemText(0, _translate("MainWindow", "----", None))
        self.behavior_combo.setItemText(1, _translate("MainWindow", "Smooth", None))
        self.behavior_combo.setItemText(2, _translate("MainWindow", "Sharp", None))
        self.behavior_combo.setItemText(3, _translate("MainWindow", "Symmetric", None))
        self.label_20.setText(_translate("MainWindow", "Vertex Behavior", None))
        self.stroke_override_nib_angle.setText(_translate("MainWindow", "Override Character Set", None))
        self.label_21.setText(_translate("MainWindow", "Nib angle", None))
        self.property_tabs.setTabText(self.property_tabs.indexOf(self.stroke_prop_tab), _translate("MainWindow", "Stroke", None))
        self.label_13.setText(_translate("MainWindow", "Note: All units are nib-widths.", None))
        self.override_char_set.setText(_translate("MainWindow", "Override Character Set", None))
        self.label_14.setText(_translate("MainWindow", "Character Width", None))
        self.label_15.setText(_translate("MainWindow", "Left spacing", None))
        self.label_16.setText(_translate("MainWindow", "Right spacing", None))
        self.property_tabs.setTabText(self.property_tabs.indexOf(self.char_prop_tab), _translate("MainWindow", "Character", None))
        self.label.setText(_translate("MainWindow", "Note: All units are nib-widths.", None))
        self.label_3.setText(_translate("MainWindow", "Capital height", None))
        self.label_4.setText(_translate("MainWindow", "Ascent height", None))
        self.label_2.setText(_translate("MainWindow", "X-height", None))
        self.label_5.setText(_translate("MainWindow", "Descent height", None))
        self.label_6.setText(_translate("MainWindow", "Guide angle", None))
        self.label_7.setText(_translate("MainWindow", "Gap distance", None))
        self.label_8.setText(_translate("MainWindow", "Nominal width", None))
        self.label_9.setText(_translate("MainWindow", "Left spacing", None))
        self.label_10.setText(_translate("MainWindow", "Right spacing", None))
        self.label_11.setText(_translate("MainWindow", "Guideline color", None))
        self.label_12.setText(_translate("MainWindow", "Nib angle", None))
        self.property_tabs.setTabText(self.property_tabs.indexOf(self.char_set_prop_tab), _translate("MainWindow", "Character Set", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Snap.setTitle(_translate("MainWindow", "&Snap", None))
        self.menu_Stroke.setTitle(_translate("MainWindow", "Stro&ke", None))
        self.menu_Glyph.setTitle(_translate("MainWindow", "&Glyph", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.file_new.setText(_translate("MainWindow", "&New", None))
        self.file_new.setToolTip(_translate("MainWindow", "Create a new character set", None))
        self.file_new.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.file_open.setText(_translate("MainWindow", "&Open", None))
        self.file_open.setToolTip(_translate("MainWindow", "Open a character set", None))
        self.file_open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.file_save.setText(_translate("MainWindow", "&Save", None))
        self.file_save.setToolTip(_translate("MainWindow", "Save the character set", None))
        self.file_save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.file_save_as.setText(_translate("MainWindow", "Save As...", None))
        self.file_save_as.setToolTip(_translate("MainWindow", "Save the character set with a new name", None))
        self.file_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.file_quit.setText(_translate("MainWindow", "&Quit", None))
        self.file_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.edit_undo.setText(_translate("MainWindow", "&Undo", None))
        self.edit_undo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.edit_redo.setText(_translate("MainWindow", "&Redo", None))
        self.edit_redo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z", None))
        self.edit_cut.setText(_translate("MainWindow", "&Cut", None))
        self.edit_cut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.edit_copy.setText(_translate("MainWindow", "C&opy", None))
        self.edit_copy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.edit_paste.setText(_translate("MainWindow", "&Paste", None))
        self.edit_paste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.view_reset_origin.setText(_translate("MainWindow", "&Reset View Origin", None))
        self.view_reset_origin.setShortcut(_translate("MainWindow", "Ctrl+.", None))
        self.view_reset_zoom.setText(_translate("MainWindow", "Zoom 100%", None))
        self.view_reset_zoom.setShortcut(_translate("MainWindow", "Ctrl+0", None))
        self.view_guides.setText(_translate("MainWindow", "&Guidelines", None))
        self.view_guides.setToolTip(_translate("MainWindow", "Toggle guidelines on/off", None))
        self.view_nib_guides.setText(_translate("MainWindow", "Nib Guides", None))
        self.view_nib_guides.setToolTip(_translate("MainWindow", "Toggle nib guides on/off", None))
        self.view_snap_to_axes.setText(_translate("MainWindow", "To Axes", None))
        self.view_snap_to_axes.setToolTip(_translate("MainWindow", "Toggle snapping to axes", None))
        self.view_snap_to_axes.setShortcut(_translate("MainWindow", "Ctrl+1", None))
        self.view_snap_to_nib_axes.setText(_translate("MainWindow", "To Nib Axes", None))
        self.view_snap_to_nib_axes.setShortcut(_translate("MainWindow", "Ctrl+2", None))
        self.view_snap_to_grid.setText(_translate("MainWindow", "To Guides", None))
        self.view_snap_to_grid.setShortcut(_translate("MainWindow", "Ctrl+3", None))
        self.view_snap_to_ctrl_pts.setText(_translate("MainWindow", "To Points", None))
        self.view_snap_to_ctrl_pts.setShortcut(_translate("MainWindow", "Ctrl+4", None))
        self.action_To_Strokes.setText(_translate("MainWindow", "To Strokes", None))
        self.action_To_Strokes.setShortcut(_translate("MainWindow", "Ctrl+5", None))
        self.stroke_new.setText(_translate("MainWindow", "&New Stroke", None))
        self.stroke_new.setToolTip(_translate("MainWindow", "Create a new stroke", None))
        self.stroke_new.setShortcut(_translate("MainWindow", "Shift+N", None))
        self.stroke_delete.setText(_translate("MainWindow", "&Delete", None))
        self.stroke_delete.setToolTip(_translate("MainWindow", "Delete selected stroke(s)", None))
        self.stroke_delete.setShortcut(_translate("MainWindow", "Backspace", None))
        self.stroke_straighten.setText(_translate("MainWindow", "Straighten", None))
        self.stroke_join.setText(_translate("MainWindow", "Join", None))
        self.stroke_flip_x.setText(_translate("MainWindow", "Flip X", None))
        self.stroke_flip_y.setText(_translate("MainWindow", "Flip Y", None))
        self.stroke_align_tangents.setText(_translate("MainWindow", "Set Tangent To Symmetric", None))
        self.stroke_smooth_tangents.setText(_translate("MainWindow", "Set Tangent To Smooth", None))
        self.stroke_sharpen_tangents.setText(_translate("MainWindow", "Set Tangent To Sharp", None))
        self.stroke_add_vertex.setText(_translate("MainWindow", "Add Control Point", None))
        self.stroke_split_at_point.setText(_translate("MainWindow", "Split At Point", None))
        self.stroke_save.setText(_translate("MainWindow", "Save Stroke(s) As Glyph", None))
        self.stroke_save.setShortcut(_translate("MainWindow", "Ctrl+Shift+C", None))
        self.help_about.setText(_translate("MainWindow", "&About", None))
        self.stroke_load.setText(_translate("MainWindow", "Paste From Saved", None))
        self.stroke_load.setShortcut(_translate("MainWindow", "Ctrl+Shift+V", None))
        self.glyph_delete.setText(_translate("MainWindow", "Delete Saved", None))

from view.paper import DrawingArea, LayoutArea
from view.widgets_qt import SelectColorButton
import pytalic2_rc
