# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytalic2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pytalic.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setContentsMargins(2, 2, 3, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.char_selector_list = QtWidgets.QListWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_selector_list.sizePolicy().hasHeightForWidth())
        self.char_selector_list.setSizePolicy(sizePolicy)
        self.char_selector_list.setMaximumSize(QtCore.QSize(16777215, 70))
        self.char_selector_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.char_selector_list.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.char_selector_list.setTabKeyNavigation(True)
        self.char_selector_list.setIconSize(QtCore.QSize(40, 40))
        self.char_selector_list.setFlow(QtWidgets.QListView.LeftToRight)
        self.char_selector_list.setUniformItemSizes(True)
        self.char_selector_list.setObjectName("char_selector_list")
        self.main_layout.addWidget(self.char_selector_list)
        self.view_layout = QtWidgets.QHBoxLayout()
        self.view_layout.setSpacing(5)
        self.view_layout.setObjectName("view_layout")
        self.stroke_selector_list = QtWidgets.QListWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_selector_list.sizePolicy().hasHeightForWidth())
        self.stroke_selector_list.setSizePolicy(sizePolicy)
        self.stroke_selector_list.setMaximumSize(QtCore.QSize(90, 16777215))
        self.stroke_selector_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.stroke_selector_list.setTabKeyNavigation(True)
        self.stroke_selector_list.setDragEnabled(True)
        self.stroke_selector_list.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.stroke_selector_list.setIconSize(QtCore.QSize(60, 60))
        self.stroke_selector_list.setUniformItemSizes(True)
        self.stroke_selector_list.setObjectName("stroke_selector_list")
        self.view_layout.addWidget(self.stroke_selector_list)
        self.main_splitter = QtWidgets.QSplitter(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_splitter.sizePolicy().hasHeightForWidth())
        self.main_splitter.setSizePolicy(sizePolicy)
        self.main_splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.main_view_tabs = QtWidgets.QTabWidget(self.main_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_view_tabs.sizePolicy().hasHeightForWidth())
        self.main_view_tabs.setSizePolicy(sizePolicy)
        self.main_view_tabs.setMouseTracking(False)
        self.main_view_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.main_view_tabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_view_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_view_tabs.setObjectName("main_view_tabs")
        self.dwg_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwg_tab.sizePolicy().hasHeightForWidth())
        self.dwg_tab.setSizePolicy(sizePolicy)
        self.dwg_tab.setAcceptDrops(True)
        self.dwg_tab.setObjectName("dwg_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dwg_tab)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dwg_area = DrawingArea(self.dwg_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwg_area.sizePolicy().hasHeightForWidth())
        self.dwg_area.setSizePolicy(sizePolicy)
        self.dwg_area.setMouseTracking(True)
        self.dwg_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dwg_area.setAcceptDrops(True)
        self.dwg_area.setFrameShape(QtWidgets.QFrame.Panel)
        self.dwg_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dwg_area.setLineWidth(2)
        self.dwg_area.setMidLineWidth(0)
        self.dwg_area.setObjectName("dwg_area")
        self.verticalLayout_2.addWidget(self.dwg_area)
        self.main_view_tabs.addTab(self.dwg_tab, "")
        self.glyph_dwg_tab = QtWidgets.QWidget()
        self.glyph_dwg_tab.setObjectName("glyph_dwg_tab")
        self.horizontalLayout = QtWidgets.QVBoxLayout(self.glyph_dwg_tab)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stroke_dwg_area = DrawingArea(self.glyph_dwg_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_dwg_area.sizePolicy().hasHeightForWidth())
        self.stroke_dwg_area.setSizePolicy(sizePolicy)
        self.stroke_dwg_area.setMouseTracking(True)
        self.stroke_dwg_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.stroke_dwg_area.setFrameShape(QtWidgets.QFrame.Panel)
        self.stroke_dwg_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stroke_dwg_area.setLineWidth(2)
        self.stroke_dwg_area.setObjectName("stroke_dwg_area")
        self.horizontalLayout.addWidget(self.stroke_dwg_area)
        self.main_view_tabs.addTab(self.glyph_dwg_tab, "")
        self.preview_tab = QtWidgets.QWidget()
        self.preview_tab.setObjectName("preview_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.preview_tab)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_reset_button = QtWidgets.QPushButton(self.preview_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_reset_button.sizePolicy().hasHeightForWidth())
        self.layout_reset_button.setSizePolicy(sizePolicy)
        self.layout_reset_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.layout_reset_button.setObjectName("layout_reset_button")
        self.horizontalLayout_2.addWidget(self.layout_reset_button)
        self.frame_layout_button = QtWidgets.QPushButton(self.preview_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_layout_button.sizePolicy().hasHeightForWidth())
        self.frame_layout_button.setSizePolicy(sizePolicy)
        self.frame_layout_button.setObjectName("frame_layout_button")
        self.horizontalLayout_2.addWidget(self.frame_layout_button)
        self.layout_combo = QtWidgets.QComboBox(self.preview_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_combo.sizePolicy().hasHeightForWidth())
        self.layout_combo.setSizePolicy(sizePolicy)
        self.layout_combo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.layout_combo.setFrame(True)
        self.layout_combo.setObjectName("layout_combo")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.layout_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.layout_combo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.preview_area = LayoutArea(self.preview_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_area.sizePolicy().hasHeightForWidth())
        self.preview_area.setSizePolicy(sizePolicy)
        self.preview_area.setMouseTracking(True)
        self.preview_area.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.preview_area.setFrameShape(QtWidgets.QFrame.Panel)
        self.preview_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.preview_area.setLineWidth(2)
        self.preview_area.setObjectName("preview_area")
        self.verticalLayout_3.addWidget(self.preview_area)
        self.main_view_tabs.addTab(self.preview_tab, "")
        self.property_tabs = QtWidgets.QTabWidget(self.main_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.property_tabs.sizePolicy().hasHeightForWidth())
        self.property_tabs.setSizePolicy(sizePolicy)
        self.property_tabs.setObjectName("property_tabs")
        self.char_prop_tab = QtWidgets.QWidget()
        self.char_prop_tab.setObjectName("char_prop_tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.char_prop_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.stroke_group_box = QtWidgets.QGroupBox(self.char_prop_tab)
        self.stroke_group_box.setObjectName("stroke_group_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stroke_group_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.stroke_group_box)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.position_x_spin = QtWidgets.QDoubleSpinBox(self.stroke_group_box)
        self.position_x_spin.setKeyboardTracking(False)
        self.position_x_spin.setDecimals(1)
        self.position_x_spin.setMinimum(-100000.0)
        self.position_x_spin.setMaximum(100000.0)
        self.position_x_spin.setObjectName("position_x_spin")
        self.horizontalLayout_6.addWidget(self.position_x_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.stroke_group_box)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.position_y_spin = QtWidgets.QDoubleSpinBox(self.stroke_group_box)
        self.position_y_spin.setKeyboardTracking(False)
        self.position_y_spin.setDecimals(1)
        self.position_y_spin.setMinimum(-100000.0)
        self.position_y_spin.setMaximum(100000.0)
        self.position_y_spin.setObjectName("position_y_spin")
        self.horizontalLayout_7.addWidget(self.position_y_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.stroke_override_nib_angle = QtWidgets.QCheckBox(self.stroke_group_box)
        self.stroke_override_nib_angle.setObjectName("stroke_override_nib_angle")
        self.horizontalLayout_8.addWidget(self.stroke_override_nib_angle)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(self.stroke_group_box)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.stroke_nib_combo = QtWidgets.QComboBox(self.stroke_group_box)
        self.stroke_nib_combo.setEnabled(False)
        self.stroke_nib_combo.setObjectName("stroke_nib_combo")
        self.stroke_nib_combo.addItem("")
        self.stroke_nib_combo.addItem("")
        self.horizontalLayout_11.addWidget(self.stroke_nib_combo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.stroke_group_box)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.stroke_nib_angle_spin = QtWidgets.QSpinBox(self.stroke_group_box)
        self.stroke_nib_angle_spin.setEnabled(False)
        self.stroke_nib_angle_spin.setWrapping(True)
        self.stroke_nib_angle_spin.setMaximum(90)
        self.stroke_nib_angle_spin.setProperty("value", 40)
        self.stroke_nib_angle_spin.setObjectName("stroke_nib_angle_spin")
        self.horizontalLayout_9.addWidget(self.stroke_nib_angle_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.stroke_group_box)
        self.vertex_group_box = QtWidgets.QGroupBox(self.char_prop_tab)
        self.vertex_group_box.setObjectName("vertex_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.vertex_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.vertex_group_box)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.vertex_x_spin = QtWidgets.QDoubleSpinBox(self.vertex_group_box)
        self.vertex_x_spin.setKeyboardTracking(False)
        self.vertex_x_spin.setDecimals(1)
        self.vertex_x_spin.setMinimum(-100000.0)
        self.vertex_x_spin.setMaximum(100000.0)
        self.vertex_x_spin.setObjectName("vertex_x_spin")
        self.horizontalLayout_3.addWidget(self.vertex_x_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.vertex_group_box)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.vertex_y_spin = QtWidgets.QDoubleSpinBox(self.vertex_group_box)
        self.vertex_y_spin.setKeyboardTracking(False)
        self.vertex_y_spin.setDecimals(1)
        self.vertex_y_spin.setMinimum(-100000.0)
        self.vertex_y_spin.setMaximum(100000.0)
        self.vertex_y_spin.setObjectName("vertex_y_spin")
        self.horizontalLayout_4.addWidget(self.vertex_y_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.vertex_group_box)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.behavior_combo = QtWidgets.QComboBox(self.vertex_group_box)
        self.behavior_combo.setFrame(True)
        self.behavior_combo.setObjectName("behavior_combo")
        self.behavior_combo.addItem("")
        self.behavior_combo.addItem("")
        self.behavior_combo.addItem("")
        self.behavior_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.behavior_combo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.vertex_group_box)
        self.character_group_box = QtWidgets.QGroupBox(self.char_prop_tab)
        self.character_group_box.setObjectName("character_group_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.character_group_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.character_group_box)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.override_char_set = QtWidgets.QCheckBox(self.character_group_box)
        self.override_char_set.setObjectName("override_char_set")
        self.horizontalLayout_12.addWidget(self.override_char_set)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.character_group_box)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.char_width_spin = QtWidgets.QDoubleSpinBox(self.character_group_box)
        self.char_width_spin.setEnabled(False)
        self.char_width_spin.setWrapping(True)
        self.char_width_spin.setDecimals(1)
        self.char_width_spin.setMinimum(1.0)
        self.char_width_spin.setMaximum(10.0)
        self.char_width_spin.setSingleStep(0.5)
        self.char_width_spin.setProperty("value", 4.0)
        self.char_width_spin.setObjectName("char_width_spin")
        self.horizontalLayout_13.addWidget(self.char_width_spin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.character_group_box)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.left_space_spin = QtWidgets.QDoubleSpinBox(self.character_group_box)
        self.left_space_spin.setEnabled(False)
        self.left_space_spin.setWrapping(True)
        self.left_space_spin.setDecimals(1)
        self.left_space_spin.setMaximum(3.0)
        self.left_space_spin.setSingleStep(0.1)
        self.left_space_spin.setProperty("value", 1.0)
        self.left_space_spin.setObjectName("left_space_spin")
        self.horizontalLayout_15.addWidget(self.left_space_spin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.character_group_box)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.right_space_spin = QtWidgets.QDoubleSpinBox(self.character_group_box)
        self.right_space_spin.setEnabled(False)
        self.right_space_spin.setWrapping(True)
        self.right_space_spin.setDecimals(1)
        self.right_space_spin.setMaximum(3.0)
        self.right_space_spin.setSingleStep(0.1)
        self.right_space_spin.setProperty("value", 1.0)
        self.right_space_spin.setObjectName("right_space_spin")
        self.horizontalLayout_14.addWidget(self.right_space_spin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.character_group_box)
        self.property_tabs.addTab(self.char_prop_tab, "")
        self.char_set_prop_tab = QtWidgets.QWidget()
        self.char_set_prop_tab.setObjectName("char_set_prop_tab")
        self.formLayout = QtWidgets.QFormLayout(self.char_set_prop_tab)
        self.formLayout.setObjectName("formLayout")
        self.nib_group_box = QtWidgets.QGroupBox(self.char_set_prop_tab)
        self.nib_group_box.setObjectName("nib_group_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.nib_group_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_12 = QtWidgets.QLabel(self.nib_group_box)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_27.addWidget(self.label_12)
        self.char_set_nib_angle_spin = QtWidgets.QSpinBox(self.nib_group_box)
        self.char_set_nib_angle_spin.setWrapping(True)
        self.char_set_nib_angle_spin.setMaximum(90)
        self.char_set_nib_angle_spin.setProperty("value", 40)
        self.char_set_nib_angle_spin.setObjectName("char_set_nib_angle_spin")
        self.horizontalLayout_27.addWidget(self.char_set_nib_angle_spin)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.nib_group_box)
        self.metrics_grpup_box = QtWidgets.QGroupBox(self.char_set_prop_tab)
        self.metrics_grpup_box.setObjectName("metrics_grpup_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.metrics_grpup_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label.setObjectName("label")
        self.horizontalLayout_16.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_2 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_17.addWidget(self.label_2)
        self.base_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.base_height_spin.setWrapping(True)
        self.base_height_spin.setFrame(True)
        self.base_height_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.base_height_spin.setDecimals(1)
        self.base_height_spin.setMinimum(1.0)
        self.base_height_spin.setMaximum(10.0)
        self.base_height_spin.setSingleStep(0.5)
        self.base_height_spin.setObjectName("base_height_spin")
        self.horizontalLayout_17.addWidget(self.base_height_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_3 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_18.addWidget(self.label_3)
        self.cap_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.cap_height_spin.setWrapping(True)
        self.cap_height_spin.setDecimals(1)
        self.cap_height_spin.setMinimum(0.5)
        self.cap_height_spin.setMaximum(10.0)
        self.cap_height_spin.setSingleStep(0.5)
        self.cap_height_spin.setProperty("value", 2.0)
        self.cap_height_spin.setObjectName("cap_height_spin")
        self.horizontalLayout_18.addWidget(self.cap_height_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        self.ascent_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.ascent_height_spin.setWrapping(True)
        self.ascent_height_spin.setDecimals(1)
        self.ascent_height_spin.setMinimum(1.0)
        self.ascent_height_spin.setMaximum(10.0)
        self.ascent_height_spin.setSingleStep(0.5)
        self.ascent_height_spin.setObjectName("ascent_height_spin")
        self.horizontalLayout_19.addWidget(self.ascent_height_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_20.addWidget(self.label_5)
        self.descent_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.descent_height_spin.setWrapping(True)
        self.descent_height_spin.setDecimals(1)
        self.descent_height_spin.setMinimum(1.0)
        self.descent_height_spin.setMaximum(10.0)
        self.descent_height_spin.setSingleStep(0.5)
        self.descent_height_spin.setObjectName("descent_height_spin")
        self.horizontalLayout_20.addWidget(self.descent_height_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_6 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_21.addWidget(self.label_6)
        self.angle_spin = QtWidgets.QSpinBox(self.metrics_grpup_box)
        self.angle_spin.setWrapping(True)
        self.angle_spin.setMaximum(45)
        self.angle_spin.setObjectName("angle_spin")
        self.horizontalLayout_21.addWidget(self.angle_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_7 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_22.addWidget(self.label_7)
        self.gap_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.gap_height_spin.setWrapping(True)
        self.gap_height_spin.setDecimals(1)
        self.gap_height_spin.setMinimum(0.5)
        self.gap_height_spin.setMaximum(4.0)
        self.gap_height_spin.setSingleStep(0.5)
        self.gap_height_spin.setProperty("value", 1.0)
        self.gap_height_spin.setObjectName("gap_height_spin")
        self.horizontalLayout_22.addWidget(self.gap_height_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_8 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_23.addWidget(self.label_8)
        self.nominal_width_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.nominal_width_spin.setWrapping(True)
        self.nominal_width_spin.setDecimals(1)
        self.nominal_width_spin.setMinimum(1.0)
        self.nominal_width_spin.setMaximum(10.0)
        self.nominal_width_spin.setSingleStep(0.5)
        self.nominal_width_spin.setProperty("value", 4.0)
        self.nominal_width_spin.setObjectName("nominal_width_spin")
        self.horizontalLayout_23.addWidget(self.nominal_width_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_9 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_24.addWidget(self.label_9)
        self.char_set_left_space_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.char_set_left_space_spin.setDecimals(1)
        self.char_set_left_space_spin.setMaximum(3.0)
        self.char_set_left_space_spin.setSingleStep(0.1)
        self.char_set_left_space_spin.setProperty("value", 1.0)
        self.char_set_left_space_spin.setObjectName("char_set_left_space_spin")
        self.horizontalLayout_24.addWidget(self.char_set_left_space_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_25.addWidget(self.label_10)
        self.char_set_right_space_spin = QtWidgets.QDoubleSpinBox(self.metrics_grpup_box)
        self.char_set_right_space_spin.setDecimals(1)
        self.char_set_right_space_spin.setMaximum(3.0)
        self.char_set_right_space_spin.setSingleStep(0.1)
        self.char_set_right_space_spin.setProperty("value", 1.0)
        self.char_set_right_space_spin.setObjectName("char_set_right_space_spin")
        self.horizontalLayout_25.addWidget(self.char_set_right_space_spin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_11 = QtWidgets.QLabel(self.metrics_grpup_box)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_26.addWidget(self.label_11)
        self.guides_color_button = SelectColorButton(self.metrics_grpup_box)
        self.guides_color_button.setAutoFillBackground(False)
        self.guides_color_button.setText("")
        self.guides_color_button.setObjectName("guides_color_button")
        self.horizontalLayout_26.addWidget(self.guides_color_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.metrics_grpup_box)
        self.property_tabs.addTab(self.char_set_prop_tab, "")
        self.view_layout.addWidget(self.main_splitter)
        self.main_layout.addLayout(self.view_layout)
        self.verticalLayout.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 15))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Transform = QtWidgets.QMenu(self.menubar)
        self.menu_Transform.setObjectName("menu_Transform")
        self.menu_Snap = QtWidgets.QMenu(self.menu_Transform)
        self.menu_Snap.setObjectName("menu_Snap")
        self.menu_Stroke = QtWidgets.QMenu(self.menubar)
        self.menu_Stroke.setObjectName("menu_Stroke")
        self.menu_Glyph = QtWidgets.QMenu(self.menubar)
        self.menu_Glyph.setObjectName("menu_Glyph")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.file_new = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/script_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_new.setIcon(icon1)
        self.file_new.setObjectName("file_new")
        self.file_open = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/script_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_open.setIcon(icon2)
        self.file_open.setObjectName("file_open")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/script_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save.setIcon(icon3)
        self.file_save.setObjectName("file_save")
        self.file_save_as = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save_as.setIcon(icon4)
        self.file_save_as.setObjectName("file_save_as")
        self.file_quit = QtWidgets.QAction(MainWindow)
        self.file_quit.setObjectName("file_quit")
        self.edit_undo = QtWidgets.QAction(MainWindow)
        self.edit_undo.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/arrow_undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_undo.setIcon(icon5)
        self.edit_undo.setObjectName("edit_undo")
        self.edit_redo = QtWidgets.QAction(MainWindow)
        self.edit_redo.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/arrow_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_redo.setIcon(icon6)
        self.edit_redo.setObjectName("edit_redo")
        self.edit_cut = QtWidgets.QAction(MainWindow)
        self.edit_cut.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_cut.setIcon(icon7)
        self.edit_cut.setObjectName("edit_cut")
        self.edit_copy = QtWidgets.QAction(MainWindow)
        self.edit_copy.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/page_white_copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_copy.setIcon(icon8)
        self.edit_copy.setObjectName("edit_copy")
        self.edit_paste = QtWidgets.QAction(MainWindow)
        self.edit_paste.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/page_white_paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_paste.setIcon(icon9)
        self.edit_paste.setObjectName("edit_paste")
        self.view_reset_origin = QtWidgets.QAction(MainWindow)
        self.view_reset_origin.setObjectName("view_reset_origin")
        self.view_reset_zoom = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/zoom_actual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_reset_zoom.setIcon(icon10)
        self.view_reset_zoom.setObjectName("view_reset_zoom")
        self.view_guides = QtWidgets.QAction(MainWindow)
        self.view_guides.setCheckable(True)
        self.view_guides.setChecked(True)
        self.view_guides.setObjectName("view_guides")
        self.view_nib_guides = QtWidgets.QAction(MainWindow)
        self.view_nib_guides.setCheckable(True)
        self.view_nib_guides.setChecked(True)
        self.view_nib_guides.setObjectName("view_nib_guides")
        self.view_snap_to_axes = QtWidgets.QAction(MainWindow)
        self.view_snap_to_axes.setCheckable(True)
        self.view_snap_to_axes.setChecked(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/transform_move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_axes.setIcon(icon11)
        self.view_snap_to_axes.setObjectName("view_snap_to_axes")
        self.view_snap_to_nib_axes = QtWidgets.QAction(MainWindow)
        self.view_snap_to_nib_axes.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/transform_path.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_nib_axes.setIcon(icon12)
        self.view_snap_to_nib_axes.setObjectName("view_snap_to_nib_axes")
        self.view_snap_to_grid = QtWidgets.QAction(MainWindow)
        self.view_snap_to_grid.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_grid.setIcon(icon13)
        self.view_snap_to_grid.setObjectName("view_snap_to_grid")
        self.view_snap_to_ctrl_pts = QtWidgets.QAction(MainWindow)
        self.view_snap_to_ctrl_pts.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/edit_path.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_snap_to_ctrl_pts.setIcon(icon14)
        self.view_snap_to_ctrl_pts.setObjectName("view_snap_to_ctrl_pts")
        self.action_To_Strokes = QtWidgets.QAction(MainWindow)
        self.action_To_Strokes.setCheckable(True)
        self.action_To_Strokes.setEnabled(False)
        self.action_To_Strokes.setObjectName("action_To_Strokes")
        self.stroke_new = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/draw_path.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stroke_new.setIcon(icon15)
        self.stroke_new.setObjectName("stroke_new")
        self.stroke_delete = QtWidgets.QAction(MainWindow)
        self.stroke_delete.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stroke_delete.setIcon(icon16)
        self.stroke_delete.setObjectName("stroke_delete")
        self.stroke_straighten = QtWidgets.QAction(MainWindow)
        self.stroke_straighten.setEnabled(False)
        self.stroke_straighten.setObjectName("stroke_straighten")
        self.stroke_join = QtWidgets.QAction(MainWindow)
        self.stroke_join.setEnabled(False)
        self.stroke_join.setObjectName("stroke_join")
        self.stroke_flip_x = QtWidgets.QAction(MainWindow)
        self.stroke_flip_x.setEnabled(False)
        self.stroke_flip_x.setObjectName("stroke_flip_x")
        self.stroke_flip_y = QtWidgets.QAction(MainWindow)
        self.stroke_flip_y.setEnabled(False)
        self.stroke_flip_y.setObjectName("stroke_flip_y")
        self.stroke_align_tangents = QtWidgets.QAction(MainWindow)
        self.stroke_align_tangents.setEnabled(False)
        self.stroke_align_tangents.setObjectName("stroke_align_tangents")
        self.stroke_smooth_tangents = QtWidgets.QAction(MainWindow)
        self.stroke_smooth_tangents.setEnabled(False)
        self.stroke_smooth_tangents.setObjectName("stroke_smooth_tangents")
        self.stroke_sharpen_tangents = QtWidgets.QAction(MainWindow)
        self.stroke_sharpen_tangents.setEnabled(False)
        self.stroke_sharpen_tangents.setObjectName("stroke_sharpen_tangents")
        self.stroke_add_vertex = QtWidgets.QAction(MainWindow)
        self.stroke_add_vertex.setEnabled(False)
        self.stroke_add_vertex.setObjectName("stroke_add_vertex")
        self.stroke_split_at_point = QtWidgets.QAction(MainWindow)
        self.stroke_split_at_point.setEnabled(False)
        self.stroke_split_at_point.setObjectName("stroke_split_at_point")
        self.stroke_save = QtWidgets.QAction(MainWindow)
        self.stroke_save.setEnabled(False)
        self.stroke_save.setObjectName("stroke_save")
        self.help_about = QtWidgets.QAction(MainWindow)
        self.help_about.setObjectName("help_about")
        self.stroke_load = QtWidgets.QAction(MainWindow)
        self.stroke_load.setEnabled(False)
        self.stroke_load.setObjectName("stroke_load")
        self.glyph_delete = QtWidgets.QAction(MainWindow)
        self.glyph_delete.setEnabled(False)
        self.glyph_delete.setObjectName("glyph_delete")
        self.edit_select_all = QtWidgets.QAction(MainWindow)
        self.edit_select_all.setEnabled(True)
        self.edit_select_all.setObjectName("edit_select_all")
        self.edit_deselect_all = QtWidgets.QAction(MainWindow)
        self.edit_deselect_all.setEnabled(False)
        self.edit_deselect_all.setObjectName("edit_deselect_all")
        self.action_constrain_to_x_axis = QtWidgets.QAction(MainWindow)
        self.action_constrain_to_x_axis.setCheckable(True)
        self.action_constrain_to_x_axis.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_constrain_to_x_axis.setIcon(icon17)
        self.action_constrain_to_x_axis.setObjectName("action_constrain_to_x_axis")
        self.action_constrain_to_y_axis = QtWidgets.QAction(MainWindow)
        self.action_constrain_to_y_axis.setCheckable(True)
        self.action_constrain_to_y_axis.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_constrain_to_y_axis.setIcon(icon18)
        self.action_constrain_to_y_axis.setObjectName("action_constrain_to_y_axis")
        self.edit_preferences = QtWidgets.QAction(MainWindow)
        self.edit_preferences.setObjectName("edit_preferences")
        self.menu_File.addAction(self.file_new)
        self.menu_File.addAction(self.file_open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.file_save)
        self.menu_File.addAction(self.file_save_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.file_quit)
        self.menu_Edit.addAction(self.edit_undo)
        self.menu_Edit.addAction(self.edit_redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.edit_cut)
        self.menu_Edit.addAction(self.edit_copy)
        self.menu_Edit.addAction(self.edit_paste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.edit_select_all)
        self.menu_Edit.addAction(self.edit_deselect_all)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.edit_preferences)
        self.menu_View.addAction(self.view_reset_origin)
        self.menu_View.addAction(self.view_reset_zoom)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.view_guides)
        self.menu_View.addAction(self.view_nib_guides)
        self.menu_View.addSeparator()
        self.menu_Snap.addAction(self.view_snap_to_axes)
        self.menu_Snap.addAction(self.view_snap_to_nib_axes)
        self.menu_Snap.addAction(self.view_snap_to_grid)
        self.menu_Snap.addAction(self.view_snap_to_ctrl_pts)
        self.menu_Snap.addAction(self.action_To_Strokes)
        self.menu_Transform.addAction(self.menu_Snap.menuAction())
        self.menu_Transform.addSeparator()
        self.menu_Transform.addAction(self.action_constrain_to_x_axis)
        self.menu_Transform.addAction(self.action_constrain_to_y_axis)
        self.menu_Stroke.addAction(self.stroke_new)
        self.menu_Stroke.addAction(self.stroke_delete)
        self.menu_Stroke.addAction(self.stroke_straighten)
        self.menu_Stroke.addAction(self.stroke_join)
        self.menu_Stroke.addAction(self.stroke_flip_x)
        self.menu_Stroke.addAction(self.stroke_flip_y)
        self.menu_Stroke.addSeparator()
        self.menu_Stroke.addAction(self.stroke_align_tangents)
        self.menu_Stroke.addAction(self.stroke_smooth_tangents)
        self.menu_Stroke.addAction(self.stroke_sharpen_tangents)
        self.menu_Stroke.addSeparator()
        self.menu_Stroke.addAction(self.stroke_add_vertex)
        self.menu_Stroke.addAction(self.stroke_split_at_point)
        self.menu_Glyph.addAction(self.stroke_save)
        self.menu_Glyph.addAction(self.stroke_load)
        self.menu_Glyph.addAction(self.glyph_delete)
        self.menu_Help.addAction(self.help_about)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Transform.menuAction())
        self.menubar.addAction(self.menu_Stroke.menuAction())
        self.menubar.addAction(self.menu_Glyph.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.file_new)
        self.toolBar.addAction(self.file_open)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.file_save)
        self.toolBar.addAction(self.file_save_as)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_undo)
        self.toolBar.addAction(self.edit_redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_cut)
        self.toolBar.addAction(self.edit_copy)
        self.toolBar.addAction(self.edit_paste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.view_snap_to_axes)
        self.toolBar.addAction(self.view_snap_to_nib_axes)
        self.toolBar.addAction(self.view_snap_to_grid)
        self.toolBar.addAction(self.view_snap_to_ctrl_pts)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.stroke_new)
        self.toolBar.addAction(self.stroke_delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_constrain_to_x_axis)
        self.toolBar.addAction(self.action_constrain_to_y_axis)

        self.retranslateUi(MainWindow)
        self.main_view_tabs.setCurrentIndex(0)
        self.property_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.dwg_tab), _translate("MainWindow", "Character"))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.glyph_dwg_tab), _translate("MainWindow", "Glyph"))
        self.layout_reset_button.setText(_translate("MainWindow", "Reset Layout"))
        self.frame_layout_button.setText(_translate("MainWindow", "Frame Layout"))
        self.layout_combo.setItemText(0, _translate("MainWindow", "ABCDEFGHIJKLMNOPQRSTUVWXYZ  abcdefghijklmnopqrstuvwxyz  0123456789"))
        self.layout_combo.setItemText(1, _translate("MainWindow", "Both fickle dwarves jinx my pig quiz"))
        self.layout_combo.setItemText(2, _translate("MainWindow", "The five boxing wizards jump quickly"))
        self.layout_combo.setItemText(3, _translate("MainWindow", "Fix problem quickly with galvanized jets"))
        self.layout_combo.setItemText(4, _translate("MainWindow", "Cozy sphinx waves quart jug of bad milk"))
        self.layout_combo.setItemText(5, _translate("MainWindow", "The quick brown fox jumps over the lazy dog"))
        self.layout_combo.setItemText(6, _translate("MainWindow", "Pack my red box with five dozen quality jugs"))
        self.layout_combo.setItemText(7, _translate("MainWindow", "Amazingly few discotheques provide jukeboxes"))
        self.layout_combo.setItemText(8, _translate("MainWindow", "Painful zombies quickly watch a jinxed graveyard"))
        self.layout_combo.setItemText(9, _translate("MainWindow", "Jack quietly moved up front and seized the big ball of wax"))
        self.main_view_tabs.setTabText(self.main_view_tabs.indexOf(self.preview_tab), _translate("MainWindow", "Preview"))
        self.stroke_group_box.setTitle(_translate("MainWindow", "Stroke"))
        self.label_18.setText(_translate("MainWindow", "X"))
        self.label_19.setText(_translate("MainWindow", "Y"))
        self.stroke_override_nib_angle.setText(_translate("MainWindow", "Override Character Set"))
        self.label_23.setText(_translate("MainWindow", "Nib type"))
        self.stroke_nib_combo.setItemText(0, _translate("MainWindow", "Italic"))
        self.stroke_nib_combo.setItemText(1, _translate("MainWindow", "Round"))
        self.label_21.setText(_translate("MainWindow", "Nib angle"))
        self.vertex_group_box.setTitle(_translate("MainWindow", "Vertex"))
        self.label_17.setText(_translate("MainWindow", "X"))
        self.label_22.setText(_translate("MainWindow", "Y"))
        self.label_20.setText(_translate("MainWindow", "Vertex behavior"))
        self.behavior_combo.setItemText(0, _translate("MainWindow", "----"))
        self.behavior_combo.setItemText(1, _translate("MainWindow", "Smooth"))
        self.behavior_combo.setItemText(2, _translate("MainWindow", "Sharp"))
        self.behavior_combo.setItemText(3, _translate("MainWindow", "Symmetric"))
        self.character_group_box.setTitle(_translate("MainWindow", "Character"))
        self.label_13.setText(_translate("MainWindow", "Note: All units are nib-widths."))
        self.override_char_set.setText(_translate("MainWindow", "Override Character Set"))
        self.label_14.setText(_translate("MainWindow", "Character Width"))
        self.label_15.setText(_translate("MainWindow", "Left spacing"))
        self.label_16.setText(_translate("MainWindow", "Right spacing"))
        self.property_tabs.setTabText(self.property_tabs.indexOf(self.char_prop_tab), _translate("MainWindow", "Character"))
        self.nib_group_box.setTitle(_translate("MainWindow", "Nib"))
        self.label_12.setText(_translate("MainWindow", "Nib angle"))
        self.metrics_grpup_box.setTitle(_translate("MainWindow", "Metrics"))
        self.label.setText(_translate("MainWindow", "Note: All units are nib-widths."))
        self.label_2.setText(_translate("MainWindow", "X-height"))
        self.label_3.setText(_translate("MainWindow", "Capital height"))
        self.label_4.setText(_translate("MainWindow", "Ascent height"))
        self.label_5.setText(_translate("MainWindow", "Descent height"))
        self.label_6.setText(_translate("MainWindow", "Guide angle"))
        self.label_7.setText(_translate("MainWindow", "Gap distance"))
        self.label_8.setText(_translate("MainWindow", "Nominal width"))
        self.label_9.setText(_translate("MainWindow", "Left spacing"))
        self.label_10.setText(_translate("MainWindow", "Right spacing"))
        self.label_11.setText(_translate("MainWindow", "Guideline color"))
        self.property_tabs.setTabText(self.property_tabs.indexOf(self.char_set_prop_tab), _translate("MainWindow", "Character Set"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menu_Transform.setTitle(_translate("MainWindow", "&Transform"))
        self.menu_Snap.setTitle(_translate("MainWindow", "&Snap"))
        self.menu_Stroke.setTitle(_translate("MainWindow", "Stro&ke"))
        self.menu_Glyph.setTitle(_translate("MainWindow", "&Glyph"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.file_new.setText(_translate("MainWindow", "&New"))
        self.file_new.setToolTip(_translate("MainWindow", "Create a new character set"))
        self.file_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.file_open.setText(_translate("MainWindow", "&Open"))
        self.file_open.setToolTip(_translate("MainWindow", "Open a character set"))
        self.file_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.file_save.setText(_translate("MainWindow", "&Save"))
        self.file_save.setToolTip(_translate("MainWindow", "Save the character set"))
        self.file_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.file_save_as.setText(_translate("MainWindow", "Save As..."))
        self.file_save_as.setToolTip(_translate("MainWindow", "Save the character set with a new name"))
        self.file_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.file_quit.setText(_translate("MainWindow", "&Quit"))
        self.file_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.edit_undo.setText(_translate("MainWindow", "&Undo"))
        self.edit_undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.edit_redo.setText(_translate("MainWindow", "&Redo"))
        self.edit_redo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.edit_cut.setText(_translate("MainWindow", "&Cut"))
        self.edit_cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.edit_copy.setText(_translate("MainWindow", "C&opy"))
        self.edit_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.edit_paste.setText(_translate("MainWindow", "&Paste"))
        self.edit_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.view_reset_origin.setText(_translate("MainWindow", "&Reset View Origin"))
        self.view_reset_origin.setShortcut(_translate("MainWindow", "Ctrl+."))
        self.view_reset_zoom.setText(_translate("MainWindow", "Zoom 100%"))
        self.view_reset_zoom.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.view_guides.setText(_translate("MainWindow", "&Guidelines"))
        self.view_guides.setToolTip(_translate("MainWindow", "Toggle guidelines on/off"))
        self.view_nib_guides.setText(_translate("MainWindow", "Nib Guides"))
        self.view_nib_guides.setToolTip(_translate("MainWindow", "Toggle nib guides on/off"))
        self.view_snap_to_axes.setText(_translate("MainWindow", "To Axes"))
        self.view_snap_to_axes.setToolTip(_translate("MainWindow", "Toggle snapping to axes"))
        self.view_snap_to_axes.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.view_snap_to_nib_axes.setText(_translate("MainWindow", "To Nib Axes"))
        self.view_snap_to_nib_axes.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.view_snap_to_grid.setText(_translate("MainWindow", "To Guides"))
        self.view_snap_to_grid.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.view_snap_to_ctrl_pts.setText(_translate("MainWindow", "To Points"))
        self.view_snap_to_ctrl_pts.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.action_To_Strokes.setText(_translate("MainWindow", "To Strokes"))
        self.action_To_Strokes.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.stroke_new.setText(_translate("MainWindow", "&New Stroke"))
        self.stroke_new.setToolTip(_translate("MainWindow", "Create a new stroke"))
        self.stroke_new.setShortcut(_translate("MainWindow", "Shift+N"))
        self.stroke_delete.setText(_translate("MainWindow", "&Delete"))
        self.stroke_delete.setToolTip(_translate("MainWindow", "Delete selected stroke(s)"))
        self.stroke_delete.setShortcut(_translate("MainWindow", "Backspace"))
        self.stroke_straighten.setText(_translate("MainWindow", "Straighten"))
        self.stroke_join.setText(_translate("MainWindow", "Join"))
        self.stroke_flip_x.setText(_translate("MainWindow", "Flip X"))
        self.stroke_flip_y.setText(_translate("MainWindow", "Flip Y"))
        self.stroke_align_tangents.setText(_translate("MainWindow", "Set Tangent To Symmetric"))
        self.stroke_smooth_tangents.setText(_translate("MainWindow", "Set Tangent To Smooth"))
        self.stroke_sharpen_tangents.setText(_translate("MainWindow", "Set Tangent To Sharp"))
        self.stroke_add_vertex.setText(_translate("MainWindow", "Add Control Point"))
        self.stroke_split_at_point.setText(_translate("MainWindow", "Split At Point"))
        self.stroke_save.setText(_translate("MainWindow", "Save Stroke(s) As Glyph"))
        self.stroke_save.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.help_about.setText(_translate("MainWindow", "&About"))
        self.stroke_load.setText(_translate("MainWindow", "Paste From Saved"))
        self.stroke_load.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.glyph_delete.setText(_translate("MainWindow", "Delete Saved"))
        self.edit_select_all.setText(_translate("MainWindow", "Select &All"))
        self.edit_select_all.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.edit_deselect_all.setText(_translate("MainWindow", "&Deselect All"))
        self.edit_deselect_all.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_constrain_to_x_axis.setText(_translate("MainWindow", "Constrain X"))
        self.action_constrain_to_x_axis.setShortcut(_translate("MainWindow", "Alt+X"))
        self.action_constrain_to_y_axis.setText(_translate("MainWindow", "Constrain Y"))
        self.action_constrain_to_y_axis.setShortcut(_translate("MainWindow", "Alt+Y"))
        self.edit_preferences.setText(_translate("MainWindow", "Preferences"))

from view.paper import DrawingArea, LayoutArea
from view.widgets_qt import SelectColorButton
import pytalic2_rc
