# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytalic2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 15))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.file_open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/script_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_open.setIcon(icon)
        self.file_open.setObjectName("file_open")
        self.file_new = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/script_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_new.setIcon(icon1)
        self.file_new.setObjectName("file_new")
        self.file_save = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/script_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save.setIcon(icon2)
        self.file_save.setObjectName("file_save")
        self.file_save_as = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_save_as.setIcon(icon3)
        self.file_save_as.setObjectName("file_save_as")
        self.file_quit = QtWidgets.QAction(MainWindow)
        self.file_quit.setObjectName("file_quit")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        self.action_Undo.setObjectName("action_Undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Cut = QtWidgets.QAction(MainWindow)
        self.action_Cut.setObjectName("action_Cut")
        self.actionCo_py = QtWidgets.QAction(MainWindow)
        self.actionCo_py.setObjectName("actionCo_py")
        self.action_Paste = QtWidgets.QAction(MainWindow)
        self.action_Paste.setObjectName("action_Paste")
        self.menuFile.addAction(self.file_new)
        self.menuFile.addAction(self.file_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_save)
        self.menuFile.addAction(self.file_save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_quit)
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.actionCo_py)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.toolBar.addAction(self.file_new)
        self.toolBar.addAction(self.file_open)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.file_save)
        self.toolBar.addAction(self.file_save_as)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.file_open.setText(_translate("MainWindow", "&Open"))
        self.file_new.setText(_translate("MainWindow", "&New"))
        self.file_save.setText(_translate("MainWindow", "&Save"))
        self.file_save_as.setText(_translate("MainWindow", "Save &As..."))
        self.file_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Undo.setText(_translate("MainWindow", "&Undo"))
        self.action_Redo.setText(_translate("MainWindow", "&Redo"))
        self.action_Cut.setText(_translate("MainWindow", "&Cut"))
        self.actionCo_py.setText(_translate("MainWindow", "Cop&y"))
        self.action_Paste.setText(_translate("MainWindow", "&Paste"))

import shared.pytalic2_rc
