# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pytalic2_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(391, 327)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 290, 371, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.metrics_group_box = QtWidgets.QGroupBox(Dialog)
        self.metrics_group_box.setGeometry(QtCore.QRect(200, 10, 181, 271))
        self.metrics_group_box.setObjectName("metrics_group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.metrics_group_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.metrics_group_box)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_3 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_18.addWidget(self.label_3)
        self.base_height_spin_2 = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.base_height_spin_2.setWrapping(True)
        self.base_height_spin_2.setFrame(True)
        self.base_height_spin_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.base_height_spin_2.setDecimals(1)
        self.base_height_spin_2.setMinimum(1.0)
        self.base_height_spin_2.setMaximum(10.0)
        self.base_height_spin_2.setSingleStep(0.5)
        self.base_height_spin_2.setObjectName("base_height_spin_2")
        self.horizontalLayout_18.addWidget(self.base_height_spin_2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        self.cap_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.cap_height_spin.setWrapping(True)
        self.cap_height_spin.setDecimals(1)
        self.cap_height_spin.setMinimum(0.5)
        self.cap_height_spin.setMaximum(10.0)
        self.cap_height_spin.setSingleStep(0.5)
        self.cap_height_spin.setProperty("value", 2.0)
        self.cap_height_spin.setObjectName("cap_height_spin")
        self.horizontalLayout_19.addWidget(self.cap_height_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_20.addWidget(self.label_5)
        self.ascent_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.ascent_height_spin.setWrapping(True)
        self.ascent_height_spin.setDecimals(1)
        self.ascent_height_spin.setMinimum(1.0)
        self.ascent_height_spin.setMaximum(10.0)
        self.ascent_height_spin.setSingleStep(0.5)
        self.ascent_height_spin.setObjectName("ascent_height_spin")
        self.horizontalLayout_20.addWidget(self.ascent_height_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_6 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_21.addWidget(self.label_6)
        self.descent_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.descent_height_spin.setWrapping(True)
        self.descent_height_spin.setDecimals(1)
        self.descent_height_spin.setMinimum(1.0)
        self.descent_height_spin.setMaximum(10.0)
        self.descent_height_spin.setSingleStep(0.5)
        self.descent_height_spin.setObjectName("descent_height_spin")
        self.horizontalLayout_21.addWidget(self.descent_height_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_7 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_22.addWidget(self.label_7)
        self.angle_spin = QtWidgets.QSpinBox(self.metrics_group_box)
        self.angle_spin.setWrapping(True)
        self.angle_spin.setMaximum(45)
        self.angle_spin.setObjectName("angle_spin")
        self.horizontalLayout_22.addWidget(self.angle_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_8 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_23.addWidget(self.label_8)
        self.gap_height_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.gap_height_spin.setWrapping(True)
        self.gap_height_spin.setDecimals(1)
        self.gap_height_spin.setMinimum(0.5)
        self.gap_height_spin.setMaximum(4.0)
        self.gap_height_spin.setSingleStep(0.5)
        self.gap_height_spin.setProperty("value", 1.0)
        self.gap_height_spin.setObjectName("gap_height_spin")
        self.horizontalLayout_23.addWidget(self.gap_height_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_9 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_24.addWidget(self.label_9)
        self.nominal_width_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.nominal_width_spin.setWrapping(True)
        self.nominal_width_spin.setDecimals(1)
        self.nominal_width_spin.setMinimum(1.0)
        self.nominal_width_spin.setMaximum(10.0)
        self.nominal_width_spin.setSingleStep(0.5)
        self.nominal_width_spin.setProperty("value", 4.0)
        self.nominal_width_spin.setObjectName("nominal_width_spin")
        self.horizontalLayout_24.addWidget(self.nominal_width_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_25.addWidget(self.label_10)
        self.char_set_left_space_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.char_set_left_space_spin.setDecimals(1)
        self.char_set_left_space_spin.setMaximum(3.0)
        self.char_set_left_space_spin.setSingleStep(0.1)
        self.char_set_left_space_spin.setProperty("value", 1.0)
        self.char_set_left_space_spin.setObjectName("char_set_left_space_spin")
        self.horizontalLayout_25.addWidget(self.char_set_left_space_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_11 = QtWidgets.QLabel(self.metrics_group_box)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_26.addWidget(self.label_11)
        self.char_set_right_space_spin = QtWidgets.QDoubleSpinBox(self.metrics_group_box)
        self.char_set_right_space_spin.setDecimals(1)
        self.char_set_right_space_spin.setMaximum(3.0)
        self.char_set_right_space_spin.setSingleStep(0.1)
        self.char_set_right_space_spin.setProperty("value", 1.0)
        self.char_set_right_space_spin.setObjectName("char_set_right_space_spin")
        self.horizontalLayout_26.addWidget(self.char_set_right_space_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.color_group_box = QtWidgets.QGroupBox(Dialog)
        self.color_group_box.setGeometry(QtCore.QRect(10, 10, 181, 158))
        self.color_group_box.setObjectName("color_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.color_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_13 = QtWidgets.QLabel(self.color_group_box)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_28.addWidget(self.label_13)
        self.guides_color_button = SelectColorButton(self.color_group_box)
        self.guides_color_button.setAutoFillBackground(False)
        self.guides_color_button.setText("")
        self.guides_color_button.setObjectName("guides_color_button")
        self.horizontalLayout_28.addWidget(self.guides_color_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_14 = QtWidgets.QLabel(self.color_group_box)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_29.addWidget(self.label_14)
        self.stroke_color_button = SelectColorButton(self.color_group_box)
        self.stroke_color_button.setAutoFillBackground(False)
        self.stroke_color_button.setText("")
        self.stroke_color_button.setObjectName("stroke_color_button")
        self.horizontalLayout_29.addWidget(self.stroke_color_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_15 = QtWidgets.QLabel(self.color_group_box)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_30.addWidget(self.label_15)
        self.special_color_stroke_button = SelectColorButton(self.color_group_box)
        self.special_color_stroke_button.setAutoFillBackground(False)
        self.special_color_stroke_button.setText("")
        self.special_color_stroke_button.setObjectName("special_color_stroke_button")
        self.horizontalLayout_30.addWidget(self.special_color_stroke_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_12 = QtWidgets.QLabel(self.color_group_box)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_27.addWidget(self.label_12)
        self.glyph_color_button = SelectColorButton(self.color_group_box)
        self.glyph_color_button.setAutoFillBackground(False)
        self.glyph_color_button.setText("")
        self.glyph_color_button.setObjectName("glyph_color_button")
        self.horizontalLayout_27.addWidget(self.glyph_color_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 181, 54))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_31.addWidget(self.label_16)
        self.handle_size_spin = QtWidgets.QSpinBox(self.groupBox)
        self.handle_size_spin.setWrapping(True)
        self.handle_size_spin.setMinimum(5)
        self.handle_size_spin.setMaximum(100)
        self.handle_size_spin.setProperty("value", 10)
        self.handle_size_spin.setObjectName("handle_size_spin")
        self.horizontalLayout_31.addWidget(self.handle_size_spin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_31)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.metrics_group_box.setTitle(_translate("Dialog", "Metrics"))
        self.label.setText(_translate("Dialog", "Note: All units are nib-widths."))
        self.label_3.setText(_translate("Dialog", "X-height"))
        self.label_4.setText(_translate("Dialog", "Capital height"))
        self.label_5.setText(_translate("Dialog", "Ascent height"))
        self.label_6.setText(_translate("Dialog", "Descent height"))
        self.label_7.setText(_translate("Dialog", "Guide angle"))
        self.label_8.setText(_translate("Dialog", "Gap distance"))
        self.label_9.setText(_translate("Dialog", "Nominal width"))
        self.label_10.setText(_translate("Dialog", "Left spacing"))
        self.label_11.setText(_translate("Dialog", "Right spacing"))
        self.color_group_box.setTitle(_translate("Dialog", "Colors"))
        self.label_13.setText(_translate("Dialog", "Guidelines"))
        self.label_14.setText(_translate("Dialog", "Main stroke"))
        self.label_15.setText(_translate("Dialog", "Drawing stroke"))
        self.label_12.setText(_translate("Dialog", "Glyph"))
        self.groupBox.setTitle(_translate("Dialog", "UI"))
        self.label_16.setText(_translate("Dialog", "Handle size"))

from editor.view.widgets_qt import SelectColorButton
